name: Lint & Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [20]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      #  Check modeler
      - name: Install dependencies
        run: npm install

      - name: Lint & Test ubuntu
        if: matrix.os == 'ubuntu-latest'
        env:
          TEST_BROWSERS: ChromeHeadless, Firefox
        run: xvfb-run npm run all

      - name: Lint & Test others
        if: matrix.os != 'ubuntu-latest'
        env:
          TEST_BROWSERS: ChromeHeadless
        run: npm run all
